# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [75]:
import torch

In [76]:
import torch
torch.__version__

'2.9.0+cpu'

Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [78]:
print("тип элементов:", t1.dtype)
print("размер:", t1.shape)
print("количество размерностей:", t1.ndim)


тип элементов: torch.int64
размер: torch.Size([10])
количество размерностей: 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [79]:
left = t[:5]
right = t[5:]
print(half1)
print(half2)


tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [80]:
mat_ones = torch.ones(3, 4)
mat_ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [81]:
pyatdva = torch.ones(5, 2, dtype=bool)
pyatdva



tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [82]:
nolpyat = torch.arange(1, 15.5, 0.5)
nolpyat


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [83]:
twenty = torch.linspace(1, 10, 20)
twenty


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [84]:
random = torch.rand(4, 3)
random


tensor([[0.4119, 0.6748, 0.4530],
        [0.2518, 0.6221, 0.6261],
        [0.4923, 0.4110, 0.2941],
        [0.2332, 0.2033, 0.9258]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [85]:
marks = torch.randint(3, 6, (100,))
marks[:15]


tensor([5, 3, 3, 4, 5, 5, 5, 3, 3, 3, 5, 4, 5, 3, 5])

Задание 11. Для тензора "школьных оценок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [86]:
print("минимум:", marks.min())
print("максимум:", marks.max())
print("среднее:", marks.float().mean())


минимум: tensor(3)
максимум: tensor(5)
среднее: tensor(4.0100)


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [87]:
mask = torch.zeros(100, dtype=bool)
mask[0:5] = True
mask[-5:] = True
mask


tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])

Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [88]:
filtered_marks = marks[edge_mask]
filtered_marks


tensor([5, 3, 3, 4, 5, 5, 3, 4, 5, 3])

Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [89]:
is_five = marks == 5
is_five


tensor([ True, False, False, False,  True,  True,  True, False, False, False,
         True, False,  True, False,  True, False, False,  True, False, False,
         True,  True, False,  True, False,  True, False,  True, False,  True,
        False,  True,  True, False, False, False, False, False, False, False,
        False, False,  True, False, False,  True,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True, False,  True, False,
        False, False,  True, False, False, False, False,  True,  True, False,
         True, False, False, False, False,  True, False, False, False, False,
        False, False,  True, False, False, False, False, False,  True, False,
        False, False, False, False,  True,  True, False, False,  True, False])

Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [90]:
only_five = marks[is_five]
only_five


tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [91]:
marks_change = marks.reshape(5, 20)
marks_change.shape


torch.Size([5, 20])

Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [92]:
a = torch.arange(2, 12).reshape(2, 5)
b = torch.ones(10).reshape(2, 5)

v_stack = torch.cat([a, b], dim=0)
print("размер:", v_stack.shape)
v_stack

размер: torch.Size([4, 5])


tensor([[ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])

Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [93]:
a2 = torch.arange(2, 10, 2).reshape(2, -1)
b2 = torch.ones(10).reshape(2, 5)

h_stack = torch.cat([a2, b2], dim=1)
print("размер:", h_stack.shape)
h_stack

размер: torch.Size([2, 7])


tensor([[2., 4., 1., 1., 1., 1., 1.],
        [6., 8., 1., 1., 1., 1., 1.]])

Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [94]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

mask = (a >= 5) & (a <= 10)
result = a[mask]
result

tensor([ 6,  9, 10])

Задание 20. Вывести первую строку матрицы из задания 18.

In [95]:
first_row = h_stack[0]
first_row

tensor([2., 4., 1., 1., 1., 1., 1.])

Задание 21. Вывести последний столбец матрицы из задания 17.

In [96]:
last_col = v_stack[:, -1]
last_col

tensor([ 6., 11.,  1.,  1.])

Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [97]:
center_part = v_stack[1:3, 1:4]
center_part

tensor([[ 8.,  9., 10.],
        [ 1.,  1.,  1.]])

Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [98]:
min_val = v_stack.min()

min_row = torch.full((1, v_stack.shape[1]), min_val)

new_vstack = torch.cat([min_row, v_stack], dim=0)
new_vstack

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])

Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [99]:
sqrt_vstack = torch.sqrt(new_vstack.float())
sqrt_vstack

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.7321, 2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000, 3.1623, 3.3166],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [100]:
new_hstack = h_stack.clone()

cond = (new_hstack % 2 == 0) | (new_hstack % 3 == 0)
new_hstack[cond] = 1
new_hstack

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])